fix: collection of projects and project article responsiveness on mobile
yanaagi/cs-expo-2023 pull request #128
Opened 2023-11-10 13:44 UTC by rnlguday

2023-11-11 02:44 UTC, LimyuA reviewed
The responsiveness for a smaller browser is good but the responsiveness for mobile devices still need improvement. Use inspect element to check for mobile responsiveness

![image](https://github.com/yanaagi/cs-expo-2023/assets/92149293/adaf3689-5793-4bef-bbaf-e653e41f1a77)

2023-11-15 09:12 UTC, jjxiv approved these changes
Checked, works as expected

2023-11-15 10:08 UTC, LimyuA requested changes
Never allow pictures and videos to change their aspect ratio kase nasisira yung itsura

2023-11-17 12:39 UTC, LimyuA approved these changes

2023-11-17 12:42 UTC, nchlnnmrvnz approved these changes

2023-11-17 12:56 UTC, merged